# version: '3'

networks:
    iae_shared_network:
        external: true

services:
    buku_nginx_proxy:
        image: jwilder/nginx-proxy
        container_name: buku_nginx_proxy
        ports:
            - "8081:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - iae_shared_network

    buku_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: buku_nginx
        # ports:
        #     - "8084:80"
        volumes:
            - ./:/var/www
        depends_on:
            - buku_app
        environment:
            - VIRTUAL_HOST=api.buku.test
        networks:
            - iae_shared_network

    buku_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: buku_app
        volumes:
            - ./:/var/www
        depends_on:
            - buku_db
            - buku_cache
        environment:
            - REDIS_PORT=6379
            - REDIS_HOST=buku_cache
        networks:
            - iae_shared_network

    buku_db:
        image: mysql:8.2
        container_name: buku_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=db_buku
        ports:
            - "33061:3306"
        volumes:
            - buku_data:/var/lib/mysql
        networks:
            - iae_shared_network

    buku_cache:
        image: redis:latest
        container_name: buku_cache
        ports:
            - "63791:6379"
        networks:
            - iae_shared_network

    buku_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: buku_phpmyadmin
        depends_on:
            - buku_db
        environment:
            - PMA_HOST=buku_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.buku.test
        networks:
            - iae_shared_network

volumes:
    buku_data:
