# version: '3'

networks:
    iae_shared_network:
        external: true

services:
    enrollment_nginx_proxy:
        image: jwilder/nginx-proxy
        container_name: enrollment_nginx_proxy
        ports:
            - "8088:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - iae_shared_network

    enrollment_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: enrollment_nginx
        # ports:
        #     - "8084:80"
        volumes:
            - ./:/var/www
        depends_on:
            - enrollment_app
        environment:
            - VIRTUAL_HOST=api.enrollment.test
        networks:
            - iae_shared_network

    enrollment_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: enrollment_app
        volumes:
            - ./:/var/www
        depends_on:
            - enrollment_db
            - enrollment_cache
        environment:
            - REDIS_PORT=6379
            - REDIS_HOST=enrollment_cache
        networks:
            - iae_shared_network

    enrollment_db:
        image: mysql:8.2
        container_name: enrollment_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=db_enroll
        ports:
            - "33066:3306"
        volumes:
            - enrollment_data:/var/lib/mysql
        networks:
            - iae_shared_network

    enrollment_cache:
        image: redis:latest
        container_name: enrollment_cache
        ports:
            - "63796:6379"
        networks:
            - iae_shared_network

    enrollment_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: enrollment_phpmyadmin
        depends_on:
            - enrollment_db
        environment:
            - PMA_HOST=enrollment_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.enrollment.test
        networks:
            - iae_shared_network

volumes:
    enrollment_data:
