# version: '3'

networks:
    iae_shared_network:
        external: true

services:
    course_nginx_proxy:
        image: jwilder/nginx-proxy
        container_name: course_nginx_proxy
        ports:
            - "8087:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - iae_shared_network

    course_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: course_nginx
        # ports:
        #     - "8084:80"
        volumes:
            - ./:/var/www
        depends_on:
            - course_app
        environment:
            - VIRTUAL_HOST=api.course.test
        networks:
            - iae_shared_network

    course_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: course_app
        volumes:
            - ./:/var/www
        depends_on:
            - course_db
            - course_cache
        environment:
            - REDIS_PORT=6379
            - REDIS_HOST=course_cache
        networks:
            - iae_shared_network

    course_db:
        image: mysql:8.2
        container_name: course_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=db_course
        ports:
            - "33062:3306"
        volumes:
            - course_data:/var/lib/mysql
        networks:
            - iae_shared_network

    course_cache:
        image: redis:latest
        container_name: course_cache
        ports:
            - "63795:6379"
        networks:
            - iae_shared_network

    course_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: course_phpmyadmin
        depends_on:
            - course_db
        environment:
            - PMA_HOST=course_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.course.test
        networks:
            - iae_shared_network

volumes:
    course_data:
