# version: "3.8"

networks:
  iae_shared_network:
    external: true

services:
    student_nginx_proxy:
        image: jwilder/nginx-proxy
        container_name: student_nginx_proxy
        ports:
            - "8084:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - iae_shared_network

    student_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: student_nginx
        # ports:
        #     - "8084:80"
        volumes:
            - ./:/var/www
        depends_on:
            - student_app
        environment:
            - VIRTUAL_HOST=api.student.test
        networks:
            - iae_shared_network

    student_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: student_app
        volumes:
            - ./:/var/www
        depends_on:
            - student_db
            - student_cache
        environment:
            - REDIS_PORT=6379
            - REDIS_HOST=student_cache
        networks:
            - iae_shared_network

    student_db:
        image: mysql:8.2
        container_name: db_student
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=db_student
        ports:
            - "33063:3306"
        volumes:
            - student_data:/var/lib/mysql
        networks:
            - iae_shared_network

    student_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: student_phpmyadmin
        depends_on:
            - student_db
        environment:
            - PMA_HOST=student_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.student.test
        networks:
            - iae_shared_network

    student_cache:
        image: redis:3.0
        container_name: student_cache
        ports:
            - "63793:6379"
        networks:
            - iae_shared_network

volumes:
    student_data:
